### ISSUE TITLE
As a developer, I understand whether I should implement Redis Cache for cost/performance reasons

### ISSUE THREAD

**Issue by rickrain** [Microsoft/entref-spring-boot#145]
_Copied from Azure Dev Ops Backlog_

After adding Redis Cache to ARM template, pipeline always times out. So adding it to backlog for now, to investigate further.
Also decide on whether Redis cache is a must for this solution.

https://dzone.com/articles/enabling-caching-in-mongodb-database-with-redis-us

**Comment by day-jeff** [comment]
I want to close this issue. Two reasons:

- CosmosDB provides performance, backed by an SLA, that is equal or better to Redis. Since we  already use CosmosDB, adding a Redis Cache layer adds unnecessary complexity.
- The team that proposed Redis Cache made an invalid assumption about how and when Redis Cache should be used. I am not aware of any concrete use case that requires Redis.
